name: fd_lints
description: An opiniated set of lint rules for Dart and Flutter projects. Made
  by yours truly Floating Dartists.
version: 2.5.0
repository: https://github.com/Floating-Dartists/fd_lints
issue_tracker: https://github.com/Floating-Dartists/fd_lints/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=7.0.0 <8.0.0"
  analyzer_plugin: ">=0.13.0 <0.14.0"
  custom_lint_builder: ">=0.7.0 <0.9.0"
