name: fd_lints
description: An opiniated set of lint rules for Dart and Flutter projects. Made by yours truly Floating Dartists.
version: 1.0.0
repository: https://github.com/Floating-Dartists/fd_lints

environment:
  sdk: ">=2.18.0 <3.0.0"
